/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";

// Chat App Actions
export const CHAT_WITH_SELECTED_USER = "CHAT_WITH_SELECTED_USER";
export const SEND_MESSAGE_TO_USER = "SEND_MESSAGE_TO_USER";
export const UPDATE_USERS_SEARCH = "UPDATE_USERS_SEARCH";
export const SEARCH_USERS = "SEARCH_USERS";
export const GET_RECENT_CHAT_USERS = "GET_RECENT_CHAT_USERS";

// Sidebar
export const TOGGLE_MENU = "TOGGLE_MENU";

// Agency Sidebar
export const AGENCY_TOGGLE_MENU = "AGENCY_TOGGLE_MENU";
export const CHANGE_AGENCY_LAYOUT_BG = "CHANGE_AGENCY_LAYOUT_BG";

// Feedbacks
export const GET_FEEDBACKS = "GET_FEEDBACKS";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";
export const GET_FEEDBACKS_FAILURE = "GET_FEEDBACKS_FAILURE";
export const GET_ALL_FEEDBACKS = "GET_ALL_FEEDBACKS";
export const ON_CHANGE_FEEDBACK_PAGE_TABS = "ON_CHANGE_FEEDBACK_PAGE_TABS";
export const MAKE_FAVORITE_FEEDBACK = "MAKE_FAVORITE_FEEDBACK";
export const ON_DELETE_FEEDBACK = "ON_DELETE_FEEDBACK";
export const VIEW_FEEDBACK_DETAILS = "VIEW_FEEDBACK_DETAILS";
export const ADD_NEW_FEEDBACK = "ADD_NEW_FEEDBACK";
export const SHOW_FEEDBACK_LOADING_INDICATOR = "SHOW_FEEDBACK_LOADING_INDICATOR";
export const HIDE_FEEDBACK_LOADING_INDICATOR = "HIDE_FEEDBACK_LOADING_INDICATOR";
export const NAVIGATE_TO_BACK = "NAVIGATE_TO_BACK";
export const REPLY_FEEDBACK = "REPLY_FEEDBACK";
export const SEND_REPLY = "SEND_REPLY";
export const UPDATE_SEARCH_IDEA = "UPDATE_SEARCH_IDEA";
export const ON_SEARCH_IDEA = "ON_SEARCH_IDEA";
export const ON_COMMENT_FEEDBACK = "ON_COMMENT_FEEDBACK";

// ecommerce
export const ON_DELETE_ITEM_FROM_CART = "ON_DELETE_ITEM_FROM_CART";
export const ON_QUANTITY_CHANGE = "ON_QUANTITY_CHANGE";
export const ON_ADD_ITEM_TO_CART = "ON_ADD_ITEM_TO_CART";

// PageContent App
export const GET_PAGE_CONTENTS = "GET_PAGE_CONTENTS";
export const GET_PAGE_CONTENTS_SUCCESS = "GET_PAGE_CONTENTS_SUCCESS";
export const GET_PAGE_CONTENTS_FAILURE = "GET_PAGE_CONTENTS_FAILURE";

// code by devang

/* ========================= MY ACCOUNT ====================================== */
/* ==================== PARTHBHAI SECTION ===================== */
//Login History List (code added by Parth Jani 18-9-2018)
export const LOGIN_HISTORY_LIST = "LOGIN_HISTORY_LIST";
export const LOGIN_HISTORY_LIST_SUCCESS = "LOGIN_HISTORY_LIST_SUCCESS";
export const LOGIN_HISTORY_LIST_FAILURE = "LOGIN_HISTORY_LIST_FAILURE";

//IP History List (code added by Parth Jani 18-9-2018)
export const IP_HISTORY_LIST = "IP_HISTORY_LIST";
export const IP_HISTORY_LIST_SUCCESS = "IP_HISTORY_LIST_SUCCESS";
export const IP_HISTORY_LIST_FAILURE = "IP_HISTORY_LIST_FAILURE";

// Device Management actions types (code added by Parth Jani 18-9-2018)
export const DEVICE_MANAGEMENT_LIST = "DEVICE_MANAGEMENT_LIST";
export const DEVICE_MANAGEMENT_LIST_SUCCESS = "DEVICE_MANAGEMENT_LIST_SUCCESS";
export const DEVICE_MANAGEMENT_LIST_FAILURE = "DEVICE_MANAGEMENT_LIST_FAILURE";

// Edit Profile actions types (code added by Parth Jani 20-9-2018)
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
//Added by salim..
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const GET_PROFILE_BY_ID_SUCCESS = "GET_PROFILE_BY_ID_SUCCESS";
export const GET_PROFILE_BY_ID_FAILURE = "GET_PROFILE_BY_ID_FAILURE";

// Edit Profile actions types (code added by Parth Jani 20-9-2018)
export const ANTI_PHISHING_CODE = "ANTI_PHISHING_CODE";
export const ANTI_PHISHING_CODE_SUCCESS = "ANTI_PHISHING_CODE_SUCCESS";
export const ANTI_PHISHING_CODE_FAILURE = "ANTI_PHISHING_CODE_FAILURE";

/* ==================== KEVINBHAI SECTION ===================== */

//For Signup User with Email
export const SIGNUP_USERS = "SIGNUP_USERS";
export const SIGNUP_USERS_SUCCESS = "SIGNUP_USERS_SUCCESS";
export const SIGNUP_USERS_FAILURE = "SIGNUP_USERS_FAILURE";

//For Signup User with Mobile
export const SIGNUP_USERS_MOBILE = "SIGNUP_USERS_MOBILE";
export const SIGNUP_USERS_MOBILE_SUCCESS = "SIGNUP_USERS_MOBILE_SUCCESS";
export const SIGNUP_USERS_MOBILE_FAILURE = "SIGNUP_USERS_MOBILE_FAILURE";

//For Signup User with Blockchain
export const SIGNUP_USERS_BLOCKCHAIN = "SIGNUP_USERS_BLOCKCHAIN";
export const SIGNUP_USERS_BLOCKCHAIN_SUCCESS = "SIGNUP_USERS_BLOCKCHAIN_SUCCESS";
export const SIGNUP_USERS_BLOCKCHAIN_FAILURE = "SIGNUP_USERS_BLOCKCHAIN_FAILURE";

//For Send Sms Auth
export const SEND_SMSAUTH = "SEND_SMSAUTH";
export const SEND_SMSAUTH_SUCCESS = "SEND_SMSAUTH_SUCCESS";
export const SEND_SMSAUTH_FAILURE = "SEND_SMSAUTH_FAILURE";

//For Send Sms Auth
export const SUBMIT_SEND_SMSAUTH = "SUBMIT_SEND_SMSAUTH";
export const SUBMIT_SEND_SMSAUTH_SUCCESS = "SUBMIT_SEND_SMSAUTH_SUCCESS";
export const SUBMIT_SEND_SMSAUTH_FAILURE = "SUBMIT_SEND_SMSAUTH_FAILURE";

//For Enable Google Auth
export const GET_GOOGLE_AUTH_INFO = "GET_GOOGLE_AUTH_INFO";
export const GET_GOOGLE_AUTH_INFO_SUCCESS = "GET_GOOGLE_AUTH_INFO_SUCCESS";
export const GET_GOOGLE_AUTH_INFO_FAILURE = "GET_GOOGLE_AUTH_INFO_FAILURE";
export const ENABLE_GOOGLE_AUTH = "ENABLE_GOOGLE_AUTH";
export const ENABLE_GOOGLE_AUTH_SUCCESS = "ENABLE_GOOGLE_AUTH_SUCCESS";
export const ENABLE_GOOGLE_AUTH_FAILURE = "ENABLE_GOOGLE_AUTH_FAILURE";

//For Reset Password
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

//For Change Password
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

//For Disable Send Sms Auth
export const DISABLE_SEND_SMSAUTH = "DISABLE_SEND_SMSAUTH";
export const DISABLE_SEND_SMSAUTH_SUCCESS = "DISABLE_SEND_SMSAUTH_SUCCESS";
export const DISABLE_SEND_SMSAUTH_FAILURE = "DISABLE_SEND_SMSAUTH_FAILURE";

//For Disable Send Sms Auth
export const DISABLE_SUBMIT_SEND_SMSAUTH = "DISABLE_SUBMIT_SEND_SMSAUTH";
export const DISABLE_SUBMIT_SEND_SMSAUTH_SUCCESS = "DISABLE_SUBMIT_SEND_SMSAUTH_SUCCESS";
export const DISABLE_SUBMIT_SEND_SMSAUTH_FAILURE = "DISABLE_SUBMIT_SEND_SMSAUTH_FAILURE";

//For Disable Send Google Auth
export const DISABLE_GOOGLE_AUTH = "DISABLE_GOOGLE_AUTH";
export const DISABLE_GOOGLE_AUTH_SUCCESS = "DISABLE_GOOGLE_AUTH_SUCCESS";
export const DISABLE_GOOGLE_AUTH_FAILURE = "DISABLE_GOOGLE_AUTH_FAILURE";

//For Membership Level
export const MEMBERSHIP_LEVEL = "MEMBERSHIP_LEVEL";
export const MEMBERSHIP_LEVEL_SUCCESS = "MEMBERSHIP_LEVEL_SUCCESS";
export const MEMBERSHIP_LEVEL_FAILURE = "MEMBERSHIP_LEVEL_FAILURE";

//For Trade Summary
export const LIST_TRADE_SUMMARY = "LIST_TRADE_SUMMARY";
export const LIST_TRADE_SUMMARY_SUCCESS = "LIST_TRADE_SUMMARY_SUCCESS";
export const LIST_TRADE_SUMMARY_FAILURE = "LIST_TRADE_SUMMARY_FAILURE";

//For Top Gainers
export const LIST_TOP_GAINERS = "LIST_TOP_GAINERS";
export const LIST_TOP_GAINERS_SUCCESS = "LIST_TOP_GAINERS_SUCCESS";
export const LIST_TOP_GAINERS_FAILURE = "LIST_TOP_GAINERS_FAILURE";

//For Top Losers
export const LIST_TOP_LOSERS = "LIST_TOP_LOSERS";
export const LIST_TOP_LOSERS_SUCCESS = "LIST_TOP_LOSERS_SUCCESS";
export const LIST_TOP_LOSERS_FAILURE = "LIST_TOP_LOSERS_FAILURE";

//For Ip Whitelist
export const LIST_IP_WHITELIST = "LIST_IP_WHITELIST";
export const LIST_IP_WHITELIST_SUCCESS = "LIST_IP_WHITELIST_SUCCESS";
export const LIST_IP_WHITELIST_FAILURE = "LIST_IP_WHITELIST_FAILURE";

//For Add IP to WhiteList
export const ADD_IP_TO_WHITELIST = "ADD_IP_TO_WHITELIST";
export const ADD_IP_TO_WHITELIST_SUCCESS = "ADD_IP_TO_WHITELIST_SUCCESS";
export const ADD_IP_TO_WHITELIST_FAILURE = "ADD_IP_TO_WHITELIST_FAILURE";

//For Delete IP to WhiteList
export const DELETE_IP_TO_WHITELIST = "DELETE_IP_TO_WHITELIST";
export const DELETE_IP_TO_WHITELIST_SUCCESS = "DELETE_IP_TO_WHITELIST_SUCCESS";
export const DELETE_IP_TO_WHITELIST_FAILURE = "DELETE_IP_TO_WHITELIST_FAILURE";

//For Disable IP to WhiteList
export const DISABLE_IP_TO_WHITELIST = "DISABLE_IP_TO_WHITELIST";
export const DISABLE_IP_TO_WHITELIST_SUCCESS = "DISABLE_IP_TO_WHITELIST_SUCCESS";
export const DISABLE_IP_TO_WHITELIST_FAILURE = "DISABLE_IP_TO_WHITELIST_FAILURE";

//For Enable IP to WhiteList
export const ENABLE_IP_TO_WHITELIST = "ENABLE_IP_TO_WHITELIST";
export const ENABLE_IP_TO_WHITELIST_SUCCESS = "ENABLE_IP_TO_WHITELIST_SUCCESS";
export const ENABLE_IP_TO_WHITELIST_FAILURE = "ENABLE_IP_TO_WHITELIST_FAILURE";

//List  WhiteList
export const LIST_DEVICE_WHITELIST = "LIST_DEVICE_WHITELIST";
export const LIST_DEVICE_WHITELIST_SUCCESS = "LIST_DEVICE_WHITELIST_SUCCESS";
export const LIST_DEVICE_WHITELIST_FAILURE = "LIST_DEVICE_WHITELIST_FAILURE";

//Add Device WhiteList
export const ADD_DEVICE_WHITELIST = "ADD_DEVICE_WHITELIST";
export const ADD_DEVICE_WHITELIST_SUCCESS = "ADD_DEVICE_WHITELIST_SUCCESS";
export const ADD_DEVICE_WHITELIST_FAILURE = "ADD_DEVICE_WHITELIST_FAILURE";

//Delete Device WhiteList
export const DELETE_DEVICE_WHITELIST = "DELETE_DEVICE_WHITELIST";
export const DELETE_DEVICE_WHITELIST_SUCCESS = "DELETE_DEVICE_WHITELIST_SUCCESS";
export const DELETE_DEVICE_WHITELIST_FAILURE = "DELETE_DEVICE_WHITELIST_FAILURE";

//Enable Device WhiteList
export const ENABLE_DEVICE_WHITELIST = "ENABLE_DEVICE_WHITELIST";
export const ENABLE_DEVICE_WHITELIST_SUCCESS = "ENABLE_DEVICE_WHITELIST_SUCCESS";
export const ENABLE_DEVICE_WHITELIST_FAILURE = "ENABLE_DEVICE_WHITELIST_FAILURE";

//Disable Device WhiteList
export const DISABLE_DEVICE_WHITELIST = "DISABLE_DEVICE_WHITELIST";
export const DISABLE_DEVICE_WHITELIST_SUCCESS = "DISABLE_DEVICE_WHITELIST_SUCCESS";
export const DISABLE_DEVICE_WHITELIST_FAILURE = "DISABLE_DEVICE_WHITELIST_FAILURE";

//Theme Configuration Get Language List
export const GET_LANGUAGE_LIST = "GET_LANGUAGE_LIST";
export const GET_LANGUAGE_LIST_SUCCESS = "GET_LANGUAGE_LIST_SUCCESS";
export const GET_LANGUAGE_LIST_FAILURE = "GET_LANGUAGE_LIST_FAILURE";

//Theme Configuration
export const SUBMIT_THEME_CONFIG = "SUBMIT_THEME_CONFIG";
export const SUBMIT_THEME_CONFIG_SUCCESS = "SUBMIT_THEME_CONFIG_SUCCESS";
export const SUBMIT_THEME_CONFIG_FAILURE = "SUBMIT_THEME_CONFIG_FAILURE";

//Forgot Confirmation
export const FORGOT_CONFIRMATION = "FORGOT_CONFIRMATION";
export const FORGOT_CONFIRMATION_SUCCESS = "FORGOT_CONFIRMATION_SUCCESS";
export const FORGOT_CONFIRMATION_FAILURE = "FORGOT_CONFIRMATION_FAILURE";

//Get Complain Type
export const GET_COMPLAIN_TYPE = "GET_COMPLAIN_TYPE";
export const GET_COMPLAIN_TYPE_SUCCESS = "GET_COMPLAIN_TYPE_SUCCESS";
export const GET_COMPLAIN_TYPE_FAILURE = "GET_COMPLAIN_TYPE_FAILURE";

/* ==================== SALIMBHAI SECTION ===================== */

//2FA Authentication
export const TWO_FA_GOOGLE_AUTHENTICATION = "TWO_FA_GOOGLE_AUTHENTICATION";
export const TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS = "TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS";
export const TWO_FA_GOOGLE_AUTHENTICATION_FAILURE = "TWO_FA_GOOGLE_AUTHENTICATION_FAILURE";
export const TWO_FA_SMS_AUTHENTICATION = "TWO_FA_SMS_AUTHENTICATION";
export const TWO_FA_SMS_AUTHENTICATION_SUCCESS = "TWO_FA_SMS_AUTHENTICATION_SUCCESS";
export const TWO_FA_SMS_AUTHENTICATION_FAILURE = "TWO_FA_SMS_AUTHENTICATION_FAILURE";
export const SEND_SMS = "SEND_SMS";
export const SEND_SMS_SUCCESS = "SEND_SMS_SUCCESS";
export const SEND_SMS_FAILURE = "SEND_SMS_FAILURE";

//Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_BLOCKCHAIN = "LOGIN_BLOCKCHAIN";
export const LOGIN_BLOCKCHAIN_SUCCESS = "LOGIN_BLOCKCHAIN_SUCCESS";
export const LOGIN_BLOCKCHAIN_FAILURE = "LOGIN_BLOCKCHAIN_FAILURE";

//Forgot Password
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

//Personal Verification Form
export const PERSONAL_VERIFICATION = "PERSONAL_VERIFICATION";
export const PERSONAL_VERIFICATION_SUCCESS = "PERSONAL_VERIFICATION_SUCCESS";
export const PERSONAL_VERIFICATION_FAILURE = "PERSONAL_VERIFICATION_FAILURE";

//Enterprise Verification Form
export const ENTERPRISE_VERIFICATION = "ENTERPRISE_VERIFICATION";
export const ENTERPRISE_VERIFICATION_SUCCESS = "ENTERPRISE_VERIFICATION_SUCCESS";
export const ENTERPRISE_VERIFICATION_FAILURE = "ENTERPRISE_VERIFICATION_FAILURE";

//Referral Friends List
export const REFERRAL_FRIENDS_LIST = "REFERRAL_FRIENDS_LIST";
export const REFERRAL_FRIENDS_SUCCESS = "REFERRAL_FRIENDS_SUCCESS";
export const REFERRAL_FRIENDS_FAILURE = "REFERRAL_FRIENDS_FAILURE";

//Referral Latest Commission History List
export const REFERRAL_LATEST_COMMISSION_HISTORY_LIST = "REFERRAL_LATEST_COMMISSION_HISTORY_LIST";
export const REFERRAL_LATEST_COMMISSION_HISTORY_SUCCESS = "REFERRAL_LATEST_COMMISSION_HISTORY_SUCCESS";
export const REFERRAL_LATEST_COMMISSION_HISTORY_FAILURE = "REFERRAL_LATEST_COMMISSION_HISTORY_FAILURE";

//Activity List
export const ACTIVITY_LIST = "ACTIVITY_LIST";
export const ACTIVITY_LIST_SUCCESS = "ACTIVITY_LIST_SUCCESS";
export const ACTIVITY_LIST_FAILURE = "ACTIVITY_LIST_FAILURE";

//API Setting Form
export const API_SETTING_CREATE = "API_SETTING_CREATE";
export const API_SETTING_CREATE_SUCCESS = "API_SETTING_CREATE_SUCCESS";
export const API_SETTING_CREATE_FAILURE = "API_SETTING_CREATE_FAILURE";
export const API_SETTING_SAVE = "API_SETTING_SAVE";
export const API_SETTING_SAVE_SUCCESS = "API_SETTING_SAVE_SUCCESS";
export const API_SETTING_SAVE_FAILURE = "API_SETTING_SAVE_FAILURE";
export const API_SETTING_EDIT = "API_SETTING_EDIT";
export const API_SETTING_EDIT_SUCCESS = "API_SETTING_EDIT_SUCCESS";
export const API_SETTING_EDIT_FAILURE = "API_SETTING_EDIT_FAILURE";
export const API_SETTING_DELETE = "API_SETTING_DELETE";
export const API_SETTING_DELETE_SUCCESS = "API_SETTING_DELETE_SUCCESS";
export const API_SETTING_DELETE_FAILURE = "API_SETTING_DELETE_FAILURE";

//Social Login
export const SOCIAL_LOGIN = "SOCIAL_LOGIN";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_FAILURE = "SOCIAL_LOGIN_FAILURE";

//Complain
export const LIST_COMPLAIN = "LIST_COMPLAIN";
export const LIST_COMPLAIN_SUCCESS = "LIST_COMPLAIN_SUCCESS";
export const LIST_COMPLAIN_FAILURE = "LIST_COMPLAIN_FAILURE";
export const ADD_COMPLAIN = "ADD_COMPLAIN";
export const ADD_COMPLAIN_SUCCESS = "ADD_COMPLAIN_SUCCESS";
export const ADD_COMPLAIN_FAILURE = "ADD_COMPLAIN_FAILURE";
export const GET_COMPLAIN_BY_ID = "GET_COMPLAIN_BY_ID";
export const GET_COMPLAIN_BY_ID_SUCCESS = "GET_COMPLAIN_BY_ID_SUCCESS";
export const GET_COMPLAIN_BY_ID_FAILURE = "GET_COMPLAIN_BY_ID_FAILURE";
export const REPLAY_COMPLAIN = "REPLAY_COMPLAIN";
export const REPLAY_COMPLAIN_SUCCESS = "REPLAY_COMPLAIN_SUCCESS";
export const REPLAY_COMPLAIN_FAILURE = "REPLAY_COMPLAIN_FAILURE";

//Normal Registration
export const NORMAL_REGISTER = "NORMAL_REGISTER";
export const NORMAL_REGISTER_SUCCESS = "NORMAL_REGISTER_SUCCESS";
export const NORMAL_REGISTER_FAILURE = "NORMAL_REGISTER_FAILURE";
export const RESEND_CONFIRMATION_LINK = "RESEND_CONFIRMATION_LINK";
export const RESEND_CONFIRMATION_LINK_SUCCESS =
    "RESEND_CONFIRMATION_LINK_SUCCESS";
export const RESEND_CONFIRMATION_LINK_FAILURE =
    "RESEND_CONFIRMATION_LINK_FAILURE";

//SignUp Email With OTP
export const SIGNUP_WITH_EMAIL = "SIGNUP_WITH_EMAIL";
export const SIGNUP_WITH_EMAIL_SUCCESS = "SIGNUP_WITH_EMAIL_SUCCESS";
export const SIGNUP_WITH_EMAIL_FAILURE = "SIGNUP_WITH_EMAIL_FAILURE";
export const SIGNUP_EMAIL_RESEND_OTP = "SIGNUP_EMAIL_RESEND_OTP";
export const SIGNUP_EMAIL_RESEND_OTP_SUCCESS = "SIGNUP_EMAIL_RESEND_OTP_SUCCESS";
export const SIGNUP_EMAIL_RESEND_OTP_FAILURE = "SIGNUP_EMAIL_RESEND_OTP_FAILURE";
export const SIGNUP_EMAIL_VERIFY_OTP = "SIGNUP_EMAIL_VERIFY_OTP";
export const SIGNUP_EMAIL_VERIFY_OTP_SUCCESS = "SIGNUP_EMAIL_VERIFY_OTP_SUCCESS";
export const SIGNUP_EMAIL_VERIFY_OTP_FAILURE = "SIGNUP_EMAIL_VERIFY_OTP_FAILURE";

//SignUp Mobile With OTP
export const SIGNUP_WITH_MOBILE = "SIGNUP_WITH_MOBILE";
export const SIGNUP_WITH_MOBILE_SUCCESS = "SIGNUP_WITH_MOBILE_SUCCESS";
export const SIGNUP_WITH_MOBILE_FAILURE = "SIGNUP_WITH_MOBILE_FAILURE";
export const SIGNUP_MOBILE_RESEND_OTP = "SIGNUP_MOBILE_RESEND_OTP";
export const SIGNUP_MOBILE_RESEND_OTP_SUCCESS = "SIGNUP_MOBILE_RESEND_OTP_SUCCESS";
export const SIGNUP_MOBILE_RESEND_OTP_FAILURE = "SIGNUP_MOBILE_RESEND_OTP_FAILURE";
export const SIGNUP_MOBILE_VERIFY_OTP = "SIGNUP_MOBILE_VERIFY_OTP";
export const SIGNUP_MOBILE_VERIFY_OTP_SUCCESS = "SIGNUP_MOBILE_VERIFY_OTP_SUCCESS";
export const SIGNUP_MOBILE_VERIFY_OTP_FAILURE = "SIGNUP_MOBILE_VERIFY_OTP_FAILURE";

//Normal Login
export const NORMAL_LOGIN = "NORMAL_LOGIN";
export const NORMAL_LOGIN_SUCCESS = "NORMAL_LOGIN_SUCCESS";
export const NORMAL_LOGIN_FAILURE = "NORMAL_LOGIN_FAILURE";

//SignIn Email With OTP
export const SIGNIN_WITH_EMAIL = "SIGNIN_WITH_EMAIL";
export const SIGNIN_WITH_EMAIL_SUCCESS = "SIGNIN_WITH_EMAIL_SUCCESS";
export const SIGNIN_WITH_EMAIL_FAILURE = "SIGNIN_WITH_EMAIL_FAILURE";
export const SIGNIN_EMAIL_RESEND_OTP = "SIGNIN_EMAIL_RESEND_OTP";
export const SIGNIN_EMAIL_RESEND_OTP_SUCCESS = "SIGNIN_EMAIL_RESEND_OTP_SUCCESS";
export const SIGNIN_EMAIL_RESEND_OTP_FAILURE = "SIGNIN_EMAIL_RESEND_OTP_FAILURE";
export const SIGNIN_EMAIL_VERIFY_OTP = "SIGNIN_EMAIL_VERIFY_OTP";
export const SIGNIN_EMAIL_VERIFY_OTP_SUCCESS = "SIGNIN_EMAIL_VERIFY_OTP_SUCCESS";
export const SIGNIN_EMAIL_VERIFY_OTP_FAILURE = "SIGNIN_EMAIL_VERIFY_OTP_FAILURE";

//SignIn Mobile With OTP
export const SIGNIN_WITH_MOBILE = "SIGNIN_WITH_MOBILE";
export const SIGNIN_WITH_MOBILE_SUCCESS = "SIGNIN_WITH_MOBILE_SUCCESS";
export const SIGNIN_WITH_MOBILE_FAILURE = "SIGNIN_WITH_MOBILE_FAILURE";
export const SIGNIN_MOBILE_RESEND_OTP = "SIGNIN_MOBILE_RESEND_OTP";
export const SIGNIN_MOBILE_RESEND_OTP_SUCCESS = "SIGNIN_MOBILE_RESEND_OTP_SUCCESS";
export const SIGNIN_MOBILE_RESEND_OTP_FAILURE = "SIGNIN_MOBILE_RESEND_OTP_FAILURE";
export const SIGNIN_MOBILE_VERIFY_OTP = "SIGNIN_MOBILE_VERIFY_OTP";
export const SIGNIN_MOBILE_VERIFY_OTP_SUCCESS = "SIGNIN_MOBILE_VERIFY_OTP_SUCCESS";
export const SIGNIN_MOBILE_VERIFY_OTP_FAILURE = "SIGNIN_MOBILE_VERIFY_OTP_FAILURE";

//Normal Login
export const GENERATE_TOKEN = "GENERATE_TOKEN";
export const GENERATE_TOKEN_SUCCESS = "GENERATE_TOKEN_SUCCESS";
export const GENERATE_TOKEN_FAILURE = "GENERATE_TOKEN_FAILURE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE";

//Signup With Block chain
export const SIGNUP_WITH_BLOCKCHAIN = "SIGNUP_WITH_BLOCKCHAIN";
export const SIGNUP_WITH_BLOCKCHAIN_SUCCESS = "SIGNUP_WITH_BLOCKCHAIN_SUCCESS";
export const SIGNUP_WITH_BLOCKCHAIN_FAILURE = "SIGNUP_WITH_BLOCKCHAIN_FAILURE";

//Email Confirmation
export const EMAIL_CONFIRMATION = "EMAIL_CONFIRMATION";
export const EMAIL_CONFIRMATION_SUCCESS = "EMAIL_CONFIRMATION_SUCCESS";
export const EMAIL_CONFIRMATION_FAILURE = "EMAIL_CONFIRMATION_FAILURE";

//Device Authorize...
export const DEVICE_AUTHORIZE = "DEVICE_AUTHORIZE";
export const DEVICE_AUTHORIZE_SUCCESS = "DEVICE_AUTHORIZE_SUCCESS";
export const DEVICE_AUTHORIZE_FAILURE = "DEVICE_AUTHORIZE_FAILURE";

/* ==================== End My Account Section ===================== */

// Actions Types For PairActions For Get Pair (tejas)
export const GET_PAIR = "GET_PAIR";
export const GET_PAIR_SUCCESS = "GET_PAIR_SUCCESS";
export const GET_PAIR_FAILURE = "GET_PAIR_FAILURE";

// Actions Types For PairActions For Update Pair (tejas)
export const UPDATE_PAIR = "UPDATE_PAIR";
export const UPDATE_PAIR_SUCCESS = "UPDATE_PAIR_SUCCESS";
export const UPDATE_PAIR_FAILURE = "UPDATE_PAIR_FAILURE";

// Actions Types For PairActions For Add Task (tejas)
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

// Actions Types For PairActions For Get Task (tejas)
export const GET_TASK = "GET_TASK";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";

// Actions Types For Pair List Actions For Get Pair  By Tejas Date : 14/9/2018
export const GET_PAIR_LIST = "GET_PAIR_LIST";
export const GET_PAIR_LIST_SUCCESS = "GET_PAIR_LIST_SUCCESS";
export const GET_PAIR_LIST_FAILURE = "GET_PAIR_LIST_FAILURE";

// Action Types For Get VolumeData By Tejas
export const GET_VOLUME_DATA = "GET_VOLUME_DATA";
export const GET_VOLUME_DATA_SUCCESS = "GET_VOLUME_DATA_SUCCESS";
export const GET_VOLUME_DATA_FAILURE = "GET_VOLUME_DATA_FAILURE";

// Actions Types For HOLDING List Actions For Get HOLDING  By Tejas Date : 14/9/2018
export const GET_HOLDING_LIST = "GET_HOLDING_LIST";
export const GET_HOLDING_LIST_SUCCESS = "GET_HOLDING_LIST_SUCCESS";
export const GET_HOLDING_LIST_FAILURE = "GET_HOLDING_LIST_FAILURE";

// Actions Types For Buyer Order List Actions For Get Buyer Order By Tejas Date : 14/9/2018
export const GET_BUYER_ORDER_LIST = "GET_BUYER_ORDER_LIST";
export const GET_BUYER_ORDER_LIST_SUCCESS = "GET_BUYER_ORDER_LIST_SUCCESS";
export const GET_BUYER_ORDER_LIST_FAILURE = "GET_BUYER_ORDER_LIST_FAILURE";
export const CHANGE_BUY_PAIR_SOCKET = "CHANGE_BUY_PAIR_SOCKET"; // added by devang parekh for re connect when pair changed

// Actions Types For Seller Order List Actions For Get Seller Order By Tejas Date : 14/9/2018
export const GET_SELLER_ORDER_LIST = "GET_SELLER_ORDER_LIST";
export const GET_SELLER_ORDER_LIST_SUCCESS = "GET_SELLER_ORDER_LIST_SUCCESS";
export const GET_SELLER_ORDER_LIST_FAILURE = "GET_SELLER_ORDER_LIST_FAILURE";
export const CHANGE_SELL_PAIR_SOCKET = "CHANGE_SELL_PAIR_SOCKET"; // added by devang parekh for re connect when pair changed

// Actions Types For Market Trade History Actions For Get Market Trade History By Tejas Date : 14/9/2018
export const GET_MARKET_TRADE_HISTORY = "GET_MARKET_TRADE_HISTORY";
export const GET_MARKET_TRADE_HISTORY_SUCCESS = "GET_MARKET_TRADE_HISTORY_SUCCESS";
export const GET_MARKET_TRADE_HISTORY_FAILURE = "GET_MARKET_TRADE_HISTORY_FAILURE";
export const CHANGE_MARKET_TRADE_HISTORY_SOCKET = "CHANGE_MARKET_TRADE_HISTORY_SOCKET"; // added by devang parekh for when change pair

// Actions Types For Active Order List Actions For Get Active Order By Tejas Date : 14/9/2018
export const GET_ACTIVE_OPEN_ORDER_LIST = "GET_ACTIVE_OPEN_ORDER_LIST";
export const GET_ACTIVE_OPEN_ORDER_LIST_SUCCESS = "GET_ACTIVE_OPEN_ORDER_LIST_SUCCESS";
export const GET_ACTIVE_OPEN_ORDER_LIST_FAILURE = "GET_ACTIVE_OPEN_ORDER_LIST_FAILURE";

// Actions Types For Active Order List Actions For Get Active Order By Tejas Date : 14/9/2018
export const GET_ACTIVE_OPEN_MY_ORDER_LIST = "GET_ACTIVE_OPEN_MY_ORDER_LIST";
export const GET_ACTIVE_OPEN_MY_ORDER_LIST_SUCCESS = "GET_ACTIVE_OPEN_MY_ORDER_LIST_SUCCESS";
export const GET_ACTIVE_OPEN_MY_ORDER_LIST_FAILURE = "GET_ACTIVE_OPEN_MY_ORDER_LIST_FAILURE";

// Actions Types For Market Cap List Actions For Get Current Market Cap By Tejas Date : 14/9/2018
export const GET_MARKET_CAP_LIST = "GET_MARKET_CAP_LIST";
export const GET_MARKET_CAP_LIST_SUCCESS = "GET_MARKET_CAP_LIST_SUCCESS";
export const GET_MARKET_CAP_LIST_FAILURE = "GET_MARKET_CAP_LIST_FAILURE";

// Actions Types For News Tickers Actions For Get Current Market Cap By Tejas Date : 14/9/2018
export const GET_NEWS_TICKER_LIST = "GET_NEWS_TICKER_LIST";
export const GET_NEWS_TICKER_LIST_SUCCESS = "GET_NEWS_TICKER_LIST_SUCCESS";
export const GET_NEWS_TICKER_LIST_FAILURE = "GET_NEWS_TICKER_LIST_FAILURE";

// Actions Types For Tickers Actions  By Tejas Date : 17/9/2018
export const GET_TICKERS_LIST = "GET_TICKERS_LIST";
export const GET_TICKERS_LIST_SUCCESS = "GET_TICKERS_LIST_SUCCESS";
export const GET_TICKERS_LIST_FAILURE = "GET_TICKERS_LIST_FAILURE";

// Actions Types For News Tickers Actions For Get Currency Detail By Tejas Date : 17/9/2018
export const GET_CURRENCY_LIST = "GET_CURRENCY_LIST";
export const GET_CURRENCY_LIST_SUCCESS = "GET_CURRENCY_LIST_SUCCESS";
export const GET_CURRENCY_LIST_FAILURE = "GET_CURRENCY_LIST_FAILURE";

// Actions Types For News Tickers Actions For Update Balance By Tejas
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAILURE = "UPDATE_BALANCE_FAILURE";

// Actions Types For Bulk Order By Tejas Date : 20/9/2018
export const DO_BULK_BUYER_ORDER = "DO_BULK_BUYER_ORDER";
export const DO_BULK_BUYER_ORDER_SUCCESS = "DO_BULK_BUYER_ORDER_SUCCESS";
export const DO_BULK_BUYER_ORDER_FAILURE = "DO_BULK_BUYER_ORDER_FAILURE";

// Actions Types For Bulk Order By Tejas Date : 20/9/2018
export const DO_BULK_SELLER_ORDER = "DO_BULK_SELLER_ORDER";
export const DO_BULK_SELLER_ORDER_SUCCESS = "DO_BULK_SELLER_ORDER_SUCCESS";
export const DO_BULK_SELLER_ORDER_FAILURE = "DO_BULK_SELLER_ORDER_FAILURE";

// Actions Types For Buy Order  By Tejas Date : 20/9/2018
export const DO_BUY_ORDER = "DO_BUY_ORDER";
export const DO_BUY_ORDER_SUCCESS = "DO_BUY_ORDER_SUCCESS";
export const DO_BUY_ORDER_FAILURE = "DO_BUY_ORDER_FAILURE";

// Actions Types For Sell Order  By Tejas Date : 20/9/2018
export const DO_SELL_ORDER = "DO_SELL_ORDER";
export const DO_SELL_ORDER_SUCCESS = "DO_SELL_ORDER_SUCCESS";
export const DO_SELL_ORDER_FAILURE = "DO_SELL_ORDER_FAILURE";

// Actions Types For Cancel Order  By Tejas Date : 21/9/2018
export const DO_CANCEL_ORDER = "DO_CANCEL_ORDER";
export const DO_CANCEL_ORDER_SUCCESS = "DO_CANCEL_ORDER_SUCCESS";
export const DO_CANCEL_ORDER_FAILURE = "DO_CANCEL_ORDER_FAILURE";

// list of action types for transaction history (devang parekh);
export const TRANSACTION_HISTORY = "TRANSACTION_HISTORY";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY_SUCCESS";
export const TRANSACTION_HISTORY_FAILURE = "TRANSACTION_HISTORY_FAILURE";
export const TRANSACTION_HISTORY_REFRESH = "TRANSACTION_HISTORY_REFRESH";
export const TRANSACTION_HISTORY_REFRESH_SUCCESS = "TRANSACTION_HISTORY_REFRESH_SUCCESS";

// list of action types for open orders (devang parekh);
export const OPEN_ORDERS = "OPEN_ORDERS";
export const OPEN_ORDERS_SUCCESS = "OPEN_ORDERS_SUCCESS";
export const OPEN_ORDERS_FAILURE = "OPEN_ORDERS_FAILURE";
export const OPEN_ORDERS_REFRESH = "OPEN_ORDERS_REFRESH";
export const OPEN_ORDERS_REFRESH_SUCCESS = "OPEN_ORDERS_REFRESH_SUCCESS";

// List Of Action types for GetChart Data (tejas)
export const GET_CHART_DATA = "GET_CHART_DATA";
export const GET_CHART_DATA_SUCCESS = "GET_CHART_DATA_SUCCESS";
export const GET_CHART_DATA_FAILURE = "GET_CHART_DATA_FAILURE";

// List Of Action types for Faq (Kushal)
export const GET_FAQ = "GET_FAQ";
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_FAILURE = "GET_FAQ_FAILURE";

export const GET_FAQ_CATEGORIES = "GET_FAQ_CATEGORIES";
export const GET_FAQ_CATEGORIES_SUCCESS = "GET_FAQ_CATEGORIES_SUCCESS";
export const GET_FAQ_CATEGORIES_FAILURE = "GET_FAQ_CATEGORIES_FAILURE";

export const GET_FAQ_QUESTIONS = "GET_FAQ_QUESTIONS";
export const GET_FAQ_QUESTIONS_SUCCESS = "GET_FAQ_QUESTIONS_SUCCESS";
export const GET_FAQ_QUESTIONS_FAILURE = "GET_FAQ_QUESTIONS_FAILURE";

export const UPDATE_SEARCH_FAQ = "UPDATE_SEARCH_FAQ";
export const ON_SEARCH_FAQ = "ON_SEARCH_FAQ";
export const SHOW_FAQ_LOADING_INDICATOR = "SHOW_FAQ_LOADING_INDICATOR";
export const HIDE_FAQ_LOADING_INDICATOR = "HIDE_FAQ_LOADING_INDICATOR";

// List Of Action types for Contact Us (Kushal)
export const ADD_NEW_CONTACTUS = "ADD_NEW_CONTACTUS";
export const ADD_CONTACTUS_SUCCESS = "ADD_CONTACTUS_SUCCESS";
export const ADD_CONTACTUS_FAILURE = "ADD_CONTACTUS_FAILURE";
export const SHOW_CONTACTUS_LOADING_INDICATOR = "SHOW_CONTACTUS_LOADING_INDICATOR";

// List Of Action types for News (Kushal)
export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";
export const GET_NEWSDETAIL = "GET_NEWSDETAIL";
export const GET_NEWSDETAIL_SUCCESS = "GET_NEWSDETAIL_SUCCESS";
export const GET_NEWSDETAIL_FAILURE = "GET_NEWSDETAIL_FAILURE";

// List Of Action types for Announcement (Kushal)
export const GET_ANNOUCEMENT = "GET_ANNOUCEMENT";
export const GET_ANNOUCEMENT_SUCCESS = "GET_ANNOUCEMENT_SUCCESS";
export const GET_ANNOUCEMENT_FAILURE = "GET_ANNOUCEMENT_FAILURE";

// List Of Action types for API (Kushal)
export const GET_API = "GET_API";
export const GET_API_SUCCESS = "GET_API_SUCCESS";
export const GET_API_FAILURE = "GET_API_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 22-09-2018
    File Comment : convert token action constants
*/
// get slab list
export const GET_CTHISTORY = "GET_CTHISTORY";
export const GET_CTHISTORY_SUCCESS = "GET_CTHISTORY_SUCCESS";
export const GET_CTHISTORY_FAILURE = "GET_CTHISTORY_FAILURE";

//convert token actions
export const GET_CTINFO = "GET_CTINFO";
export const GET_CTINFO_SUCCESS = "GET_CTINFO_SUCCESS";
export const GET_CTINFO_FAILURE = "GET_CTINFO_FAILURE";

//convert token actions
export const SUBMIT_CTREQUEST = "SUBMIT_CTREQUEST";
export const SUBMIT_CTREQUEST_SUCCESS = "SUBMIT_CTREQUEST_SUCCESS";
export const SUBMIT_CTREQUEST_FAILURE = "SUBMIT_CTREQUEST_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 13-09-2018
    Comment : App Redux Action Types for deposit
*/
// Deposit History
export const GET_DEPOSIT_HISTORY = "GET_DEPOSIT_HISTORY";
export const GET_DEPOSIT_HISTORY_SUCCESS = "GET_DEPOSIT_HISTORY_SUCCESS";
export const GET_DEPOSIT_HISTORY_FAILURE = "GET_DEPOSIT_HISTORY_FAILURE";

//Get Balance action for deposit
export const GET_AD_CURRENCY = "GET_AD_CURRENCY";
export const GET_AD_CURRENCY_SUCCESS = "GET_AD_CURRENCY_SUCCESS";
export const GET_AD_CURRENCY_FAILURE = "GET_AD_CURRENCY_FAILURE";
//Deposit Address Generation
export const GET_AD_WALLETS = "GET_AD_WALLETS";
export const GET_AD_WALLETS_SUCCESS = "GET_AD_WALLETS_SUCCESS";
export const GET_AD_WALLETS_FAILURE = "GET_AD_WALLETS_FAILURE";
//GET BALANCE FOR WITHDRAW
export const GET_AD_BALANCE = "GET_AD_BALANCE";
export const GET_AD_BALANCE_SUCCESS = "GET_AD_BALANCE_SUCCESS";
export const GET_AD_BALANCE_FAILURE = "GET_AD_BALANCE_FAILURE";
//GET DEFAULT ADDRESS OF WALLET
export const GET_DEFAULT_ADD = "GET_DEFAULT_ADD";
export const GET_DEFAULT_ADD_SUCCESS = "GET_DEFAULT_ADD_SUCCESS";
export const GET_DEFAULT_ADD_FAILURE = "GET_DEFAULT_ADD_FAILURE";
// GENERATE ADDRESS
export const GENERATE_ADDRESS = "GENERATE_ADDRESS";
export const GENERATE_ADDRESS_SUCCESS = "GENERATE_ADDRESS_SUCCESS";
export const GENERATE_ADDRESS_FAILURE = "GENERATE_ADDRESS_FAILURE";

//Get Balance action for deposit
export const GET_BALANCE = "GET_BALANCE";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILURE = "GET_BALANCE_FAILURE";
// export const REFRESH_BALANCE = 'REFRESH_BALANCE';

/* 
    Developer : Nishant Vadgam
    Date : 25-09-2018
    File Comment : Constant for LImists control actions
*/

export const GET_LC_WALLETS = "GET_LC_WALLETS";
export const GET_LC_WALLETS_SUCCESS = "GET_LC_WALLETS_SUCCESS";
export const GET_LC_WALLETS_FAILURE = "GET_LC_WALLETS_FAILURE";

//get details from server
export const GET_LIMITINFO = "GET_LIMITINFO";
export const GET_LIMITINFO_SUCCES = "GET_LIMITINFO_SUCCESS";
export const GET_LIMITINFO_FAILURE = "GET_LIMITINFO_FAILURE";

//post details to server
export const POST_LIMITINFO = "POST_LIMITINFO";
export const POST_LIMITINFO_SUCCESS = "POST_LIMITINFO_SUCCESS";
export const POST_LIMITINFO_FAILURE = "POST_LIMITINFO_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 21-09-2018
    File Comment : list of constant for token staking actions
*/
// get plan slab list...
export const GET_SLABLIST = "GET_SLABLIST";
export const GET_SLABLIST_SUCCESS = "GET_SLABLIST_SUCCESS";
export const GET_SLABLIST_FAILURE = "GET_SLABLIST_FAILURE";

// get pre confirmation
export const PRECONFIRMATIONDETAILS = "PRECONFIRMATIONDETAILS";
export const PRECONFIRMATIONDETAILS_SUCCESS = "PRECONFIRMATIONDETAILS_SUCCESS";
export const PRECONFIRMATIONDETAILS_FAILURE = "PRECONFIRMATIONDETAILS_FAILURE";

// stack request
export const STAKREQUEST = "STAKREQUEST";
export const STAKREQUEST_SUCCESS = "STAKREQUEST_SUCCESS";
export const STAKREQUEST_FAILURE = "STAKREQUEST_FAILURE";

//get wallet type list
export const GETWALLETTYPELIST = "GETWALLETTYPELIST";
export const GETWALLETTYPELIST_SUCCESS = "GETWALLETTYPELIST_SUCCESS";
export const GETWALLETTYPELIST_FAILURE = "GETWALLETTYPELIST_FAILURE";

// get staking history
export const GET_STAKHISTORY = "GET_STAKHISTORY";
export const GET_STAKHISTORY_SUCCESS = "GET_STAKHISTORY_SUCCESS";
export const GET_STAKHISTORY_FAILURE = "GET_STAKHISTORY_FAILURE";
//===================TransferIn Actions======================================
export const GET_INTERNALTRANSFER_HISTORY = "GET_INTERNALTRANSFER_HISTORY";
export const GET_INTERNALTRANSFER_HISTORY_SUCCESS = "GET_INTERNALTRANSFER_HISTORY_SUCCESS";
export const GET_INTERNALTRANSFER_HISTORY_FAILURE = "GET_INTERNALTRANSFER_HISTORY_FAILURE";

//===================TransferOut Actions======================================
export const GET_EXTERNALTRANSFER_HISTORY = "GET_EXTERNALTRANSFER_HISTORY";
export const GET_EXTERNALTRANSFER_HISTORY_SUCCESS = "GET_EXTERNALTRANSFERT_HISTORY_SUCCESS";
export const GET_EXTERNALTRANSFER_HISTORY_FAILURE = "GET_EXTERNALTRANSFER_HISTORY_FAILURE";

/* 
    Developer : Nishant Vadgama
    Date : 13-09-2018
    Comment :  App Redux Action Types for Withdraw 
*/
//Get Withdraw History
export const GET_WITHDRAW_HISTORY = "GET_WITHDRAW_HISTORY";
export const GET_WITHDRAW_HISTORY_SUCCESS = "GET_WITHDRAW_HISTORY_SUCCESS";
export const GET_WITHDRAW_HISTORY_FAILURE = "GET_WITHDRAW_HISTORY_FAILURE";
//Get Balance action for deposit
export const GET_WD_CURRENCY = "GET_WD_CURRENCY";
export const GET_WD_CURRENCY_SUCCESS = "GET_WD_CURRENCY_SUCCESS";
export const GET_WD_CURRENCY_FAILURE = "GET_WD_CURRENCY_FAILURE";
//GET WALLETS FOR WITHDRAW
export const GET_WD_WALLETS = "GET_WD_WALLETS";
export const GET_WD_WALLETS_SUCCESS = "GET_WD_WALLETS_SUCCESS";
export const GET_WD_WALLETS_FAILURE = "GET_WD_WALLETS_FAILURE";
//GET BALANCE FOR WITHDRAW
export const GET_WD_BALANCE = "GET_WD_BALANCE";
export const GET_WD_BALANCE_SUCCESS = "GET_WD_BALANCE_SUCCESS";
export const GET_WD_BALANCE_FAILURE = "GET_WD_BALANCE_FAILURE";
//GET FEE AND LIMIT FOR WITHDRAW
export const GET_FEEANDLIMIT = "GET_FEEANDLIMIT";
export const GET_FEEANDLIMIT_SUCCESS = "GET_FEEANDLIMIT_SUCCESS";
export const GET_FEEANDLIMIT_FAILURE = "GET_FEEANDLIMIT_FAILURE";
// withdraw request
export const DO_WITHDRAW = "DO_WITHDRAW";
export const DO_WITHDRAW_SUCCESS = "DO_WITHDRAW_SUCCESS";
export const DO_WITHDRAW_FAILURE = "DO_WITHDRAW_FAILURE";
// list address by walletid
export const ADDRESSBYWALLETID = "ADDRESSBYWALLETID";
export const ADDRESSBYWALLETID_SUCCESS = "ADDRESSBYWALLETID_SUCCESS";
export const ADDRESSBYWALLETID_FAILURE = "ADDRESSBYWALLETID_FAILURE";

// added by devang parekh for close socket connection
export const CLOSE_SOCKET_CONNECTION = "CLOSE_SOCKET_CONNECTION";

/* Decentralize Address Generation Constants - added by nishant */
// get currency list
export const GET_CURRENCY = "GET_CURRENCY";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE";

/// added By Tejas For Get Current Price
export const GET_CURRENT_PRICE = "GET_CURRENT_PRICE";
export const GET_CURRENT_PRICELIST_SUCCESS = "GET_CURRENT_PRICE_SUCCESS";
export const GET_CURRENT_PRICE_FAILURE = "GET_CURRENT_PRICE_FAILURE";

// post data to generate address
export const DECENT_ADDRESS_GENERATION = "DECENT_ADDRESS_GENERATION";
export const DECENT_ADDRESS_GEN_SUCCESS = "DECENT_ADDRESS_GEN_SUCCESS";
export const DECENT_ADDRESS_GEN_FAILURE = "DECENT_ADDRESS_GEN_FAILURE";

/* Address Whitelist */
// GET COIN LIST
export const GET_COIN_LIST = "GET_COIN_LIST";
export const GET_COIN_LIST_SUCCESS = "GET_COIN_LIST_SUCCESS";
export const GET_COIN_LIST_FAILURE = "GET_COIN_LIST_FAILURE";
// GET GLOBAL PREFERENCE
export const GET_PREFERENCE = "GET_PREFERENCE";
export const GET_PREFERENCE_SUCCESS = "GET_PREFERENCE_SUCCESS";
export const GET_PREFERENCE_FAILURE = "GET_PREFERENCE_FAILURE";
// SET GLOBAL PREFERENCE
export const SET_PREFERENCE = "SET_PREFERENCE";
export const SET_PREFERENCE_SUCCESS = "SET_PREFERENCE_SUCCESS";
export const SET_PREFERENCE_FAILURE = "SET_PREFERENCE_FAILURE";
// add
export const SUBMIT_WITHDRAWALADDRESSES = "SUBMIT_WITHDRAWALADDRESSES";
export const SUBMIT_WITHDRAWALADDRESSES_SUCCESS = "SUBMIT_WITHDRAWALADDRESSES_SUCCESS";
export const SUBMIT_WITHDRAWALADDRESSES_FAIL = "SUBMIT_WITHDRAWALADDRESSES_FAIL";
// list
export const FETCH_WITHDRAWALADDRESS = "FETCH_WITHDRAWALADDRESS";
export const FETCH_WITHDRAWALADDRESS_SUCCESS = "FETCH_WITHDRAWALADDRESS_SUCCESS";
export const FETCH_WITHDRAWALADDRESS_FAIL = "FETCH_WITHDRAWALADDRESS_FAIL";
// add to whitelist 
export const ADDTO_WHITELIST = "ADDTO_WHITELIST";
export const ADDTO_WHITELIST_SUCCESS = "ADDTO_WHITELIST_SUCCESS";
export const ADDTO_WHITELIST_FAILURE = "ADDTO_WHITELIST_FAILURE";
// remove form whitelis
export const REMOVE_WHITELIST = "REMOVE_WHITELIST";
export const REMOVE_WHITELIST_SUCCESS = "REMOVE_WHITELIST_SUCCESS";
export const REMOVE_WHITELIST_FAILURE = "REMOVE_WHITELIST_FAILURE";
// delete from whitelis;
export const DELETE_ADDRESSES = "DELETE_ADDRESSES";
export const DELETE_ADDRESSES_SUCCESS = "DELETE_ADDRESSES_SUCCESS";
export const DELETE_ADDRESSES_FAILURE = "DELETE_ADDRESSES_FAILURE";

// Added By Tejas For Transaction Charge report
export const GET_TRANSACTION_CHARGE = "GET_TRANSACTION_CHARGE";
export const GET_TRANSACTION_CHARGE_SUCCESS = "GET_TRANSACTION_CHARGE_SUCCESS";
export const GET_TRANSACTION_CHARGE_FAILURE = "GET_TRANSACTION_CHARGE_FAILURE";

// list of action types for Trading Ledger (Nirmit);
export const TRADING_LEDGER = "TRADING_LEDGER";
export const TRADING_LEDGER_SUCCESS = "TRADING_LEDGER_SUCCESS";
export const TRADING_LEDGER_FAILURE = "TRADING_LEDGER_FAILURE";
export const TRADING_LEDGER_REFRESH = "TRADING_LEDGER_REFRESH";
export const TRADING_LEDGER_REFRESH_SUCCESS = "TRADING_LEDGER_REFRESH_SUCCESS";

/* 
    Developer : Nishant Vadgama
    Date : 25-10-2018
    Constant for fund balance page
*/
// get total balance of all wallets
export const GET_ALL_BALANCE = "GET_ALL_BALANCE";
export const GET_ALL_BALANCE_SUCCESS = "GET_ALL_BALANCE_SUCCESS";
export const GET_ALL_BALANCE_FAILURE = "GET_ALL_BALANCE_FAILURE";
// get seprated balance by coin
export const GET_WALLETBALANCE = "GET_WALLETBALANCE";
export const GET_WALLETBALANCE_SUCCESS = "GET_WALLETBALANCE_SUCCESS";
export const GET_WALLETBALANCE_FAILURE = "GET_WALLETBALANCE_FAILURE";

//OutGoing Transaction
export const GET_OUTGOINGTRANSACTION_REPORT = "GET_OUTGOINGTRANSACTION_REPORT";
export const GET_OUTGOINGTRANSACTION_REPORT_SUCCESS = "GET_OUTGOINGTRANSACTION_REPORT_SUCCESS";
export const GET_OUTGOINGTRANSACTION_REPORT_FAILURE = "GET_OUTGOINGTRANSACTION_REPORT_FAILURE";

//Incoming Transactions
export const GET_INCOMINGTRANSACTONS_REPORT = "GET_INCOMINGTRANSACTONS_REPORT";
export const GET_INCOMINGTRANSACTONS_REPORT_SUCCESS = "GET_INCOMINGTRANSACTONS_REPORT_SUCCESS";
export const GET_INCOMINGTRANSACTONS_REPORT_FAILURE = "GET_INCOMINGTRANSACTONS_REPORT_FAILURE";

// Added By Tejas
// list of action types for My Ledger (Nirmit);
export const MY_LEDGER = "MY_LEDGER";
export const MY_LEDGER_SUCCESS = "MY_LEDGER_SUCCESS";
export const MY_LEDGER_FAILURE = "MY_LEDGER_FAILURE";

//Added By Kushal
// list of Action Type for Coinlist
export const GET_COINLIST = "GET_COINLIST";
export const GET_COINLIST_SUCCESS = "GET_COINLIST_SUCCESS";
export const GET_COINLIST_FAILURE = "GET_COINLIST_FAILURE";

// code added by devang parekh for favourite pair process
export const GET_FAVOURITE_PAIR_LIST = "GET_FAVOURITE_PAIR_LIST";
export const GET_FAVOURITE_PAIR_LIST_SUCCESS = "GET_FAVOURITE_PAIR_LIST_SUCCESS";
export const GET_FAVOURITE_PAIR_LIST_FAILED = "GET_FAVOURITE_PAIR_LIST_FAILED";
export const ADD_PAIR_TO_FAVOURITE_PAIR = "ADD_PAIR_TO_FAVOURITE_PAIR";
export const ADD_PAIR_TO_FAVOURITE_PAIR_SUCCESS = "ADD_PAIR_TO_FAVOURITE_PAIR_SUCCESS";
export const ADD_PAIR_TO_FAVOURITE_PAIR_FAILED = "ADD_PAIR_TO_FAVOURITE_PAIR_FAILED";
export const REMOVE_PAIR_FROM_FAVOURITE_PAIR = "REMOVE_PAIR_FROM_FAVOURITE_PAIR";
export const REMOVE_PAIR_FROM_FAVOURITE_PAIR_SUCCESS = "REMOVE_PAIR_FROM_FAVOURITE_PAIR_SUCCESS";
export const REMOVE_PAIR_FROM_FAVOURITE_PAIR_FAILED = "REMOVE_PAIR_FROM_FAVOURITE_PAIR_FAILED";

/* Withdrawal 2FA - added by Nishant */
export const WITHDRAWA2FAAUTH = "WITHDRAWA2FAAUTH";
export const WITHDRAWA2FAAUTH_SUCCESS = "WITHDRAWA2FAAUTH_SUCCESS";
export const WITHDRAWA2FAAUTH_FAILURE = "WITHDRAWA2FAAUTH_FAILURE";

/* Withdrawal Confirmation - added by Nishant */
export const WITHDRAWCONFRIMATION = "WITHDRAWCONFRIMATION";
export const WITHDRAWCONFRIMATION_SUCCESS = "WITHDRAWCONFRIMATION_SUCCESS";
export const WITHDRAWCONFRIMATION_FAILURE = "WITHDRAWCONFRIMATION_FAILURE";

/* wallet sharing - added by Nishant */
export const LISTALLWALLETS = "LISTALLWALLETS";
export const LISTALLWALLETS_SUCCESS = "LISTALLWALLETS_SUCCESS";
export const LISTALLWALLETS_FAILURE = "LISTALLWALLETS_FAILURE";
/* wallet user list - added by Nishant */
export const LISTWALLETUSERS = "LISTWALLETUSERS";
export const LISTWALLETUSERS_SUCCESS = "LISTWALLETUSERS_SUCCESS";
export const LISTWALLETUSERS_FAILURE = "LISTWALLETUSERS_FAILURE";
/* add wallet user - added by Nishant */
export const ADDWALLETUSER = "ADDWALLETUSER";
export const ADDWALLETUSER_SUCCESS = "ADDWALLETUSER_SUCCESS";
export const ADDWALLETUSER_FAILURE = "ADDWALLETUSER_FAILURE";
/* add wallet user - added by Nishant */
export const ACCEPTREJECTWALLETREQUEST = "ACCEPTREJECTWALLETREQUEST";
export const ACCEPTREJECTWALLETREQUEST_SUCCESS = "ACCEPTREJECTWALLETREQUEST_SUCCESS";
export const ACCEPTREJECTWALLETREQUEST_FAILURE = "ACCEPTREJECTWALLETREQUEST_FAILURE";

/* ========================= Social Profile ====================================== */
/* ==================== KEVIN SECTION ===================== */
//Edit Leader Configuration - 19/12/2018
export const EDIT_LEADER_CONFIG = "EDIT_LEADER_CONFIG";
export const EDIT_LEADER_CONFIG_SUCCESS = "EDIT_LEADER_CONFIG_SUCCESS";
export const EDIT_LEADER_CONFIG_FAILURE = "EDIT_LEADER_CONFIG_FAILURE";

//Edit Follower Configuration - 19/12/2018
export const EDIT_FOLLOWER_CONFIG = "EDIT_FOLLOWER_CONFIG";
export const EDIT_FOLLOWER_CONFIG_SUCCESS = "EDIT_FOLLOWER_CONFIG_SUCCESS";
export const EDIT_FOLLOWER_CONFIG_FAILURE = "EDIT_FOLLOWER_CONFIG_FAILURE";

//Get Follower Configuration (Salim Deraiya) - 27/12/2018
export const GET_FOLLOWER_CONFIG = "GET_FOLLOWER_CONFIG";
export const GET_FOLLOWER_CONFIG_SUCCESS = "GET_FOLLOWER_CONFIG_SUCCESS";
export const GET_FOLLOWER_CONFIG_FAILURE = "GET_FOLLOWER_CONFIG_FAILURE";

//Get Leader Configuration (Salim Deraiya) - 27/12/2018
export const GET_LEADER_CONFIG = "GET_LEADER_CONFIG";
export const GET_LEADER_CONFIG_SUCCESS = "GET_LEADER_CONFIG_SUCCESS";
export const GET_LEADER_CONFIG_FAILURE = "GET_LEADER_CONFIG_FAILURE";

//Get Social Profile Subscription (Salim Deraiya) - 24/12/2018
export const GET_SOCIAL_PROFILE_SUBSCRIPTION = "GET_SOCIAL_PROFILE_SUBSCRIPTION";
export const GET_SOCIAL_PROFILE_SUBSCRIPTION_SUCCESS = "GET_SOCIAL_PROFILE_SUBSCRIPTION_SUCCESS";
export const GET_SOCIAL_PROFILE_SUBSCRIPTION_FAILURE = "GET_SOCIAL_PROFILE_SUBSCRIPTION_FAILURE";

//Social Profile Subscribe (Salim Deraiya) - 24/12/2018
export const SOCIAL_PROFILE_SUBSCRIBE = "SOCIAL_PROFILE_SUBSCRIBE";
export const SOCIAL_PROFILE_SUBSCRIBE_SUCCESS = "SOCIAL_PROFILE_SUBSCRIBE_SUCCESS";
export const SOCIAL_PROFILE_SUBSCRIBE_FAILURE = "SOCIAL_PROFILE_SUBSCRIBE_FAILURE";

//Social Profile UnSubscribe (Salim Deraiya) - 24/12/2018
export const SOCIAL_PROFILE_UNSUBSCRIBE = "SOCIAL_PROFILE_UNSUBSCRIBE";
export const SOCIAL_PROFILE_UNSUBSCRIBE_SUCCESS = "SOCIAL_PROFILE_UNSUBSCRIBE_SUCCESS";
export const SOCIAL_PROFILE_UNSUBSCRIBE_FAILURE = "SOCIAL_PROFILE_UNSUBSCRIBE_FAILURE";

//Get Social Trading Policy Configuration - 24/12/2018
export const GET_SOCIAL_TRADING_POLICY = "GET_SOCIAL_TRADING_POLICY";
export const GET_SOCIAL_TRADING_POLICY_SUCCESS = "GET_SOCIAL_TRADING_POLICY_SUCCESS";
export const GET_SOCIAL_TRADING_POLICY_FAILURE = "GET_SOCIAL_TRADING_POLICY_FAILURE";

// code added by devang parekh 26-12-2018 for handle coin slider module
export const COIN_SLIDER_LIST = "COIN_SLIDER_LIST";
export const COIN_SLIDER_LIST_SUCCESS = "COIN_SLIDER_LIST_SUCCESS";
export const COIN_SLIDER_LIST_FAILURE = "COIN_SLIDER_LIST_FAILURE";
//Language Configuration Get Language List from Node API added by Jayesh 11-12-2018
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_FAILURE = "GET_LANGUAGES_FAILURE";

// Survey Form Added by Kushal 17-12-2018
export const GET_SURVEY = "GET_SURVEY";
export const GET_SURVEY_SUCCESS = "GET_SURVEY_SUCCESS";
export const GET_SURVEY_FAILURE = "GET_SURVEY_FAILURE";
export const ADD_SURVEYRESULT = "ADD_SURVEYRESULT";
export const ADD_SURVEYRESULT_SUCCESS = "ADD_SURVEYRESULT_SUCCESS";
export const ADD_SURVEYRESULT_FAILURE = "ADD_SURVEYRESULT_FAILURE";
export const GET_SURVEY_RESULTS_BY_ID = "GET_SURVEY_RESULTS_BY_ID";
export const GET_SURVEY_RESULTS_BY_ID_SUCCESS = "GET_SURVEY_RESULTS_BY_ID_SUCCESS";
export const GET_SURVEY_RESULTS_BY_ID_FAILURE = "GET_SURVEY_RESULTS_BY_ID_FAILURE";
//CMS Regions - Kushal 28-12-2018
export const GET_REGIONS = "GET_REGIONS";
export const GET_REGIONS_SUCCESS = "GET_REGIONS_SUCCESS";
export const GET_REGIONS_FAILURE = "GET_REGIONS_FAILURE";


//added by tejas for Top Gainers and Losers Data Date : 4-1-2019
export const GET_TOP_GAINERS_DATA = "GET_TOP_GAINERS_DATA";
export const GET_TOP_GAINERS_DATA_SUCCESS = "GET_TOP_GAINERS_DATA_SUCCESS";
export const GET_TOP_GAINERS_DATA_FAILURE = "GET_TOP_GAINERS_DATA_FAILURE";

export const GET_TOP_GAINERS_LOSERS_DATA = "GET_TOP_GAINERS_LOSERS_DATA";
export const GET_TOP_GAINERS_LOSERS_DATA_SUCCESS = "GET_TOP_GAINERS_LOSERS_DATA_SUCCESS";
export const GET_TOP_GAINERS_LOSERS_DATA_FAILURE = "GET_TOP_GAINERS_LOSERS_DATA_FAILURE";

export const GET_TOP_LOSERS_DATA = "GET_TOP_LOSERS_DATA";
export const GET_TOP_LOSERS_DATA_SUCCESS = "GET_TOP_LOSERS_DATA_SUCCESS";
export const GET_TOP_LOSERS_DATA_FAILURE = "GET_TOP_LOSERS_DATA_FAILURE";

// Actions Types For Pair List Actions For Get Pair  By Tejas 
export const GET_PAIR_LIST_DATA = "GET_PAIR_LIST_DATA";
export const GET_PAIR_LIST_DATA_SUCCESS = "GET_PAIR_LIST_DATA_SUCCESS";
export const GET_PAIR_LIST_DATA_FAILURE = "GET_PAIR_LIST_DATA_FAILURE";


//For Trade Summary Report
export const GET_TRADE_SUMMARY_DATA = "GET_TRADE_SUMMARY_DATA";
export const GET_TRADE_SUMMARY_DATA_SUCCESS = "GET_TRADE_SUMMARY_DATA_SUCCESS";
export const GET_TRADE_SUMMARY_DATA_FAILURE = "GET_TRADE_SUMMARY_DATA_FAILURE";

//CMS HelpCenter - Jayesh 09-01-2019
export const GET_HELPMANUALMODUALS = "GET_HELPMANUALMODUALS";
export const GET_HELPMANUALMODUALS_SUCCESS = "GET_HELPMANUALMODUALS_SUCCESS";
export const GET_HELPMANUALMODUALS_FAILURE = "GET_HELPMANUALMODUALS_FAILURE";
export const GET_HELPMANUALS_BY_ID = "GET_HELPMANUALS_BY_ID";
export const GET_HELPMANUALS_BY_ID_SUCCESS = "GET_HELPMANUALS_BY_ID_SUCCESS";
export const GET_HELPMANUALS_BY_ID_FAILURE = "GET_HELPMANUALS_BY_ID_FAILURE";

export const UPDATE_SEARCH_HELP = "UPDATE_SEARCH_HELP";
export const ON_SEARCH_HELP = "ON_SEARCH_HELP";
export const SHOW_HELP_LOADING_INDICATOR = "SHOW_HELP_LOADING_INDICATOR";
export const HIDE_HELP_LOADING_INDICATOR = "HIDE_HELP_LOADING_INDICATOR";


// Bharat Jograna
export const GET_DATA = "GET_DATA";
export const DATA_RECEIVED = "DATA_RECEIVED";
export const ADD_DATA = "ADD_DATA";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";